### ISSUE TITLE
Consider implementing a function similar to hslogger's getLogger?

### ISSUE THREAD

**Issue by ghost** [iosphere/elm-logger#1]
https://hackage.haskell.org/package/hslogger-1.2.10/docs/System-Log-Logger.html#v:getLogger

Thanks for considering.

**Comment by felixLam** [comment]
Hi @kanishka-azimi,

could you be a bit more specific: what do you expect the function to do?

Feel free to open a PR.

Kind regards,

Felix

**Comment by ghost** [comment]
A first version might be a function that creates a logger that will always prepend some string.

**Comment by felixLam** [comment]
Will close this issue as you can achieve this by wrapping the logger calls in your own module as explained in the readme and the sample app.
